spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://localhost:3306/bt01
        name:
        username: root
        password: password
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        database: MYSQL
        show-sql: true
        hibernate:
            ddl-auto: validate